name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Updation depencencies
        uses: Borales/actions-yarn@v3.0.0
        with:
          cmd: install --frozen-lockfile

      - name: Linting
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: lint:js

      - name: Testing
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: test

      - name: Build
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build
